default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: new
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dbBlog_on_rails_development

test:
  adapter: postgresql
  encoding: unicode
  database: dbBlog_on_rails
  pool: 5
  username: root
  password: new
  host: localhost

production:
  <<: *default
  database: dbBlog_on_rails_production
  username: root_prod_user
  password: <%= ENV['new'] %>
