name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dbBlog_on_rails
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true

      - name: Prepare DB
        run: |
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test
          
      - name: Reinstall pg gem
        run: |
          gem uninstall pg --all --executables
          gem install pg -v "~> 1.6"

      - name: Run tests
        run: bin/rails test
        
      - name: Remove cached gems
        run: |
          bundle clean --force
          rm -rf vendor/bundle

      - name: Install dependencies
        run: |
          gem install pg -v "~> 1.6" -- --with-pg-config=/usr/bin/pg_config
          bundle install --jobs 4 --retry 3
